### ISSUE TITLE
HTTP errors on Windows

### ISSUE THREAD

**Issue by roblourens** [microsoft/node-request-light#1]
After I started using request-light instead of the http module to query Chrome for its debug targets, several users on Windows reported getting HTTP errors in this issue https://github.com/Microsoft/vscode-chrome-debug/issues/237. They reported getting 504, 403, and 401 where previously it had been working for them, and they could open the url in a browser.

In this case my code looks like this: https://github.com/Microsoft/vscode-chrome-debug-core/blob/v2.0.2/src/utils.ts#L222 which is basically copied from where vscode-node-debug uses it to download sourcemaps. Below on line 240 is the original code, and when I switched back to that, it worked again. It's very simple, the url was something like `http://127.0.0.1:9222/json`. I was never able to repro it. Looking at what request-light does, it looks like it should behave the same as the basic http.get. Any idea why this would happen?

**Comment by aeschli** [comment]
Closing as this is a very old issue. Please reopen if you still see this.
